apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- webhook/service.yaml
- webhook/mutating_webhook.yaml
- deployment.yaml
